#!/usr/bin/env node
/**
 * @hook ss.statusline.ensure
 * @version 0.1.0
 * @event SessionStart
 * @plugin devops
 * @description Enables the native usage source. Installs a STABLE launcher that
 *   resolves the latest plugin `statusline-usage.js` at run time, and registers
 *   it as the user's `statusLine` — but ONLY when none is configured yet (never
 *   clobbers a custom status line). The launcher maps Claude Code's `rate_limits`
 *   JSON onto ~/.claude/usage-live.json on every status-line render, keeping the
 *   usage data minute-fresh with no Edge scrape and no extra Claude turn.
 *
 *   Idempotent: rewrites the launcher each session (so it always points at the
 *   current logic) and only adds the statusLine entry when absent.
 */

const { readFileSync, writeFileSync, existsSync } = require("node:fs");
const { join } = require("node:path");
const { homedir } = require("node:os");

const HOME = homedir();
const SETTINGS_PATH = join(HOME, ".claude", "settings.json");
const LAUNCHER_PATH = join(HOME, ".claude", "devops-statusline.cjs");

// Path to the script in THIS checkout — used as the dev/marketplace fallback
// when there is no versioned cache layout to glob.
const localScript = join(__dirname, "..", "..", "scripts", "statusline-usage.js");

// The launcher lives at a STABLE path and resolves the newest versioned
// statusline-usage.js at run time. An in-session plugin-cache rebuild
// (ss.plugin.update under a fresh version dir, old one removed) would dangle a
// baked version path — the launcher avoids that the same way ss.git.sync avoids
// it for the cron, but cross-platform (no shell globbing in the statusLine cmd).
const launcherSource = `#!/usr/bin/env node
// AUTO-GENERATED by ss.statusline.ensure — do not edit. Resolves the latest
// devops plugin statusline-usage.js and runs it (stdin in / status line out).
const fs = require('node:fs'), path = require('node:path'), os = require('node:os');
const base = path.join(os.homedir(), '.claude', 'plugins', 'cache', 'dotclaude', 'devops');
let target = ${JSON.stringify(localScript)};
try {
  const versions = fs.readdirSync(base)
    .filter(d => /^\\d+\\.\\d+\\.\\d+/.test(d))
    .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));
  for (let i = versions.length - 1; i >= 0; i--) {
    const p = path.join(base, versions[i], 'scripts', 'statusline-usage.js');
    if (fs.existsSync(p)) { target = p; break; }
  }
} catch { /* fall back to baked path */ }
// main() is guarded by require.main===module for direct runs, so call it
// explicitly here since we load the script via require().
try { const m = require(target); if (m && typeof m.main === 'function') m.main(); } catch { process.stdout.write(''); }
`;

try {
  writeFileSync(LAUNCHER_PATH, launcherSource);
} catch (err) {
  console.error(`[dotclaude] statusline launcher write failed: ${err.message}`);
  process.exit(0);
}

// Load (or start) user settings. Unlike ss.permissions.ensure we DO create a
// settings file when absent — the native usage source needs the statusLine
// entry to work at all, and an otherwise-empty settings.json is harmless.
let settings = {};
if (existsSync(SETTINGS_PATH)) {
  try {
    settings = JSON.parse(readFileSync(SETTINGS_PATH, "utf8"));
  } catch {
    process.exit(0); // unparseable — don't risk corrupting it
  }
}

if (settings.statusLine) {
  // Respect an existing status line. If it isn't ours, tell the user how to opt
  // in to the live usage writer; otherwise refresh nothing (launcher is current).
  const cmd = (settings.statusLine && settings.statusLine.command) || "";
  if (!cmd.includes("devops-statusline")) {
    console.error(
      "[dotclaude] A custom statusLine is set — leaving it untouched. To get the " +
      `live usage battery, route the status JSON through "${LAUNCHER_PATH}".`,
    );
  }
  process.exit(0);
}

settings.statusLine = {
  type: "command",
  command: `node "${LAUNCHER_PATH}"`,
  padding: 0,
};

try {
  writeFileSync(SETTINGS_PATH, JSON.stringify(settings, null, 2) + "\n");
  console.error("[dotclaude] Registered native usage statusLine — usage data now minute-fresh, no scrape.");
} catch (err) {
  console.error(`[dotclaude] Could not update ${SETTINGS_PATH}: ${err.message}`);
}
