import { describe, test, expect } from "vitest";
import {
  BUDGETS,
  classify,
  countLines,
  isGenerated,
  editDelta,
  evaluate,
  buildSummary,
  buildInstruction,
} from "./claude-file-budget.js";

const lines = n => Array.from({ length: n }, (_, i) => `line ${i}`).join("\n") + "\n";

describe("classify", () => {
  test.each([
    ["CLAUDE.md", "claude-md"],
    ["/repo/CLAUDE.md", "claude-md"],
    ["/repo/.claude/CLAUDE.md", "claude-md"],
    ["/home/u/.claude/CLAUDE.md", "claude-md"],
    ["plugins/devops/skills/ship/SKILL.md", "skill"],
    ["/repo/.claude/skills/ship/SKILL.md", "skill"],
    ["plugins/devops/agents/po.md", "agent"],
    ["/repo/.claude/agents/reviewer.md", "agent"],
    ["plugins/devops/skills/ship/reference.md", "reference"],
    ["/repo/.claude/skills/ship/reference.md", "reference"],
    ["plugins/devops/deep-knowledge/merge-safety.md", "deep-knowledge"],
    ["plugins/devops/skills/concept/deep-knowledge/templates.md", "deep-knowledge"],
  ])("%s → %s", (file, kind) => {
    expect(classify(file)).toBe(kind);
  });

  test("Windows separators classify identically", () => {
    expect(classify("C:\\repo\\plugins\\devops\\skills\\ship\\SKILL.md")).toBe("skill");
    expect(classify("C:\\repo\\CLAUDE.md")).toBe("claude-md");
  });

  // The whitelist is the anti-noise property: a catch-all over `.claude/`
  // would drag in settings, generated maps, and caches, and false positives
  // train everyone to ignore the hook.
  test.each([
    ["/repo/.claude/settings.json"],
    ["/repo/.claude/project-map.md"],
    ["/repo/README.md"],
    ["/repo/docs/architecture.md"],
    ["/repo/plugins/devops/CONVENTIONS.md"],
    ["/repo/src/index.js"],
    ["/repo/notes/reference.md"], // reference.md outside a skill dir
    [""],
    [null],
  ])("%s is not Claude context", file => {
    expect(classify(file)).toBeNull();
  });

  test("every classified kind has a budget entry", () => {
    for (const kind of ["claude-md", "skill", "agent", "reference", "deep-knowledge"]) {
      expect(BUDGETS[kind], `missing budget for ${kind}`).toBeTruthy();
      expect(BUDGETS[kind].remedy.length, `${kind} needs a written remedy`).toBeGreaterThan(40);
    }
  });
});

describe("countLines", () => {
  test.each([
    ["", 0],
    ["a", 1],
    ["a\n", 1],
    ["a\nb", 2],
    ["a\nb\n", 2],
    [null, 0],
  ])("%j → %i", (content, expected) => {
    expect(countLines(content)).toBe(expected);
  });

  test("matches wc -l semantics on a generated block", () => {
    expect(countLines(lines(25))).toBe(25);
  });
});

describe("isGenerated", () => {
  test("marker in the head exempts the file", () => {
    expect(isGenerated("<!-- AUTO-GENERATED by gen-dk-index.js -->\n# Index\n")).toBe(true);
    expect(isGenerated("# Map\n<!-- DO NOT EDIT -->\n")).toBe(true);
  });

  // Prose *about* generated files must not exempt itself — CONVENTIONS.md
  // documents the marker, and exempting it would silence a real budget.
  test("marker deep in the body does not exempt", () => {
    const body = "# Conventions\n" + lines(20) + "Files carry AUTO-GENERATED markers.\n";
    expect(isGenerated(body)).toBe(false);
  });

  test("no marker at all", () => {
    expect(isGenerated("# CLAUDE.md\n\n## Build\n")).toBe(false);
  });
});

describe("editDelta", () => {
  test("Write reports unknown magnitude", () => {
    expect(editDelta("Write", { content: lines(80) })).toBeNull();
  });

  test("Edit computes growth from the replaced fragment", () => {
    expect(editDelta("Edit", { old_string: "a", new_string: "a\nb\nc" })).toBe(2);
    expect(editDelta("Edit", { old_string: "a\nb\nc", new_string: "a" })).toBe(-2);
    expect(editDelta("Edit", { old_string: "foo", new_string: "bar" })).toBe(0);
  });

  test("replace_all: non-positive stays measured, positive becomes unknown", () => {
    // A shrinking replacement stays shrinking however often it repeats.
    expect(editDelta("Edit", { old_string: "a\nb", new_string: "a", replace_all: true })).toBe(0);
    // A growing one grows by an unknown multiple — treated as unknown.
    expect(editDelta("Edit", { old_string: "a", new_string: "a\nb", replace_all: true })).toBeNull();
  });

  test("malformed payload degrades to unknown, never throws", () => {
    expect(editDelta("Edit", {})).toBeNull();
    expect(editDelta("Edit", null)).toBeNull();
  });
});

describe("evaluate", () => {
  test("under budget is silent", () => {
    const r = evaluate({ file: "/repo/CLAUDE.md", content: lines(20), delta: 5 });
    expect(r.severity).toBe("ok");
    expect(r.silent).toBe(true);
  });

  test("over budget and growing reports", () => {
    const r = evaluate({ file: "/repo/CLAUDE.md", content: lines(40), delta: 12 });
    expect(r.severity).toBe("warn");
    expect(r.silent).toBe(false);
    expect(r.lines).toBe(40);
    expect(r.budget).toBe(25);
  });

  // The core anti-noise rule. Without it, every edit to an already-large file
  // fires — including the edits that are shrinking it.
  test("over budget but shrinking is silent", () => {
    const r = evaluate({ file: "/repo/CLAUDE.md", content: lines(40), delta: -8 });
    expect(r.severity).toBe("warn");
    expect(r.silent).toBe(true);
    expect(r.reason).toBe("not-growing");
  });

  test("over budget with a net-zero edit is silent", () => {
    const r = evaluate({ file: "/repo/CLAUDE.md", content: lines(40), delta: 0 });
    expect(r.silent).toBe(true);
  });

  test("unknown delta (a full Write) is treated as growth", () => {
    const r = evaluate({ file: "/repo/CLAUDE.md", content: lines(40), delta: null });
    expect(r.grew).toBe(true);
    expect(r.silent).toBe(false);
  });

  test("past the hard ceiling escalates to critical", () => {
    const r = evaluate({ file: "/repo/CLAUDE.md", content: lines(60), delta: 1 });
    expect(r.severity).toBe("critical");
  });

  test("deep-knowledge has a soft trigger and no ceiling", () => {
    expect(BUDGETS["deep-knowledge"].critical).toBeNull();
    const r = evaluate({
      file: "/repo/plugins/devops/deep-knowledge/x.md",
      content: lines(5000),
      delta: 1,
    });
    expect(r.severity).toBe("warn");
  });

  test("generated files are exempt at any size", () => {
    const r = evaluate({
      file: "/repo/plugins/devops/deep-knowledge/INDEX.md",
      content: "<!-- AUTO-GENERATED by gen-dk-index.js -->\n" + lines(900),
      delta: null,
    });
    expect(r.silent).toBe(true);
    expect(r.reason).toBe("generated");
  });

  test("non-Claude files never evaluate", () => {
    const r = evaluate({ file: "/repo/src/index.js", content: lines(5000), delta: null });
    expect(r.kind).toBeNull();
    expect(r.silent).toBe(true);
  });

  test("each kind trips at its own budget, not a shared one", () => {
    const at = (file, n) => evaluate({ file, content: lines(n), delta: 1 }).severity;
    expect(at("/repo/CLAUDE.md", 26)).toBe("warn");
    expect(at("/repo/skills/x/SKILL.md", 26)).toBe("ok");
    expect(at("/repo/skills/x/SKILL.md", 251)).toBe("warn");
    expect(at("/repo/agents/x.md", 151)).toBe("warn");
    expect(at("/repo/skills/x/reference.md", 201)).toBe("warn");
    expect(at("/repo/deep-knowledge/x.md", 601)).toBe("warn");
  });
});

describe("messages", () => {
  const file = "/repo/plugins/devops/skills/ship/SKILL.md";
  const result = evaluate({ file, content: lines(300), delta: 40 });

  test("summary carries file, size, budget and growth", () => {
    const s = buildSummary(file, result);
    expect(s).toContain("SKILL.md");
    expect(s).toContain("300");
    expect(s).toContain("250");
    expect(s).toContain("+40");
    expect(s).toContain("WARNING");
  });

  test("instruction names the path, the remedy target and the norm", () => {
    const i = buildInstruction(file, result);
    expect(i).toContain(file);
    expect(i).toContain("deep-knowledge");
    expect(i).toContain("content-conventions.md");
  });

  test("critical instruction states the ceiling", () => {
    const crit = evaluate({ file, content: lines(600), delta: 40 });
    expect(buildInstruction(file, crit)).toContain("500");
    expect(buildSummary(file, crit)).toContain("CRITICAL");
  });

  test("a full rewrite is named as such rather than given a fake delta", () => {
    const rewritten = evaluate({ file, content: lines(300), delta: null });
    expect(buildSummary(file, rewritten)).toContain("full rewrite");
    expect(buildSummary(file, rewritten)).not.toContain("+null");
    expect(buildInstruction(file, rewritten)).toContain("rewritten in full");
  });

  // basename and label collide for CLAUDE.md / SKILL.md / reference.md — the
  // summary must not read "CLAUDE.md is 40 lines (CLAUDE.md budget 25)".
  test("summary does not repeat the file kind", () => {
    const s = buildSummary("/repo/CLAUDE.md", evaluate({ file: "/repo/CLAUDE.md", content: lines(40), delta: 3 }));
    expect(s.match(/CLAUDE\.md/g)).toHaveLength(1);
  });
});
