import { describe, test, expect } from "vitest";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const { allEntries, renderBlock, applyBlock, BLOCK_START, BLOCK_END, PLUGIN_STATE } = require("./runtime-ignores.js");

const count = (text, marker) => text.split("\n").filter((l) => l.startsWith(marker)).length;

describe("runtime-ignores — the one list of project-rooted runtime paths", () => {
  test("every entry is a .claude/ path and none is shared configuration", () => {
    for (const e of allEntries()) expect(e.startsWith(".claude/"), e).toBe(true);
    for (const tracked of [".claude/settings.json", ".claude/graphify.json", ".claude/skills/", ".claude/project-map.md"]) {
      expect(allEntries()).not.toContain(tracked);
    }
    expect(PLUGIN_STATE).toContain(".claude/devops-config.json");
  });

  test("an empty file gets exactly one block", () => {
    const out = applyBlock("");
    expect(count(out, BLOCK_START)).toBe(1);
    expect(count(out, BLOCK_END)).toBe(1);
    expect(out.endsWith("\n")).toBe(true);
  });

  test("idempotent — a second pass changes nothing", () => {
    const once = applyBlock("# git ls-files --others --exclude-from=.git/info/exclude\n*.bak\n");
    expect(applyBlock(once)).toBe(once);
  });

  test("user lines around the block survive; an outdated block is replaced in place", () => {
    const old = ["*.bak", `${BLOCK_START} — generated by /setup-project, do not edit >>>`, ".claude/batch.md", `${BLOCK_END} <<<`, "local-notes/"].join("\n");
    const out = applyBlock(old);
    expect(out.startsWith("*.bak\n")).toBe(true);
    expect(out.trimEnd().endsWith("local-notes/")).toBe(true);
    expect(count(out, BLOCK_START)).toBe(1);
    expect(out).toContain(".claude/devops-config.json");
  });

  test("a stray START without END is left alone with everything after it", () => {
    const broken = [`${BLOCK_START} >>>`, "mine/", "also-mine/"].join("\n");
    const first = applyBlock(broken);
    expect(first).toContain("mine/\nalso-mine/");
    // The next pass must replace only the appended block, not swallow the user lines.
    const second = applyBlock(first);
    expect(second).toBe(first);
    expect(second).toContain("also-mine/");
  });

  test("CRLF input compares equal to its LF form", () => {
    const lf = applyBlock("x\n");
    expect(applyBlock(lf.replace(/\n/g, "\r\n"))).toBe(lf);
  });

  test("renderBlock lists Claude Code state before plugin state", () => {
    const block = renderBlock();
    expect(block.indexOf(".claude/worktrees/")).toBeLessThan(block.indexOf(".claude/batch.md"));
  });

  test("AUD-013: writeJsonAtomic's temp files are covered", () => {
    expect(PLUGIN_STATE).toContain(".claude/*.tmp");
    expect(allEntries()).toContain(".claude/*.tmp");
  });
});

describe("AUD-016: the run-contract store's sibling files are ignored", () => {
  test("lock, stale-lock, quarantine and pending-marker names are covered", async () => {
    const { execFileSync } = await import("node:child_process");
    const fs = (await import("node:fs")).default;
    const os = (await import("node:os")).default;
    const path = (await import("node:path")).default;
    expect(PLUGIN_STATE).toContain(".claude/run-contract.json.*");
    const d = fs.mkdtempSync(path.join(os.tmpdir(), "w2-ign-"));
    try {
      execFileSync("git", ["init", "-q"], { cwd: d });
      fs.writeFileSync(path.join(d, ".git", "info", "exclude"), renderBlock() + "\n");
      const names = [
        ".claude/run-contract.json.lock",
        ".claude/run-contract.json.lock.stale-123-abcdef",
        ".claude/run-contract.json.corrupt-1790000000000-123-abcdef",
        ".claude/run-contract.json.corrupt.pending",
        ".claude/run-contract.json",
      ];
      const out = execFileSync("git", ["check-ignore", "--no-index", ...names], { cwd: d, encoding: "utf8" });
      expect(out.trim().split(/\r?\n/)).toEqual(names);
    } finally { fs.rmSync(d, { recursive: true, force: true }); }
  });
});
